### ISSUE TITLE
KKGridViewHeader & KKGridViewFooter are the same

### ISSUE THREAD

**Issue by jonsterling** [kolinkrewinkel/KKGridView#10]
Currently, these two classes have the exact same interface an implementation. Steps:
1. Group them under a common superclass (about to commit).
2. Ask whether we will need them to be different in the future. If the answer is no, then we ought to just delete these two classes and use just one.

Thoughts?

**Comment by kolinkrewinkel** [comment]
i was considering that but i was lazy :S go ahead and do the former..
