### ISSUE TITLE
GridView not refreshing when loading elements asynchronously

### ISSUE THREAD

**Issue by jorfermo** [kolinkrewinkel/KKGridView#102]
Hi

I'm fetching an array of items asynchronously and calling [self.gridView reloadData] after completion.

If I do it this way, the gridView doesn't show any items until I scroll or press any interface item. It also refresh the date if I change the orientation on the device.

If I do that call synchronously everything works.

Any Idea why?

**Comment by jonsterling** [comment]
So, you're sending `-reloadData` from a background queue or something?

**Comment by jorfermo** [comment]
This is the kind of code I'm using. This method is called to retrieve more
items for the grid:

-(void) getItems {
    UIApplication\* app = [UIApplication sharedApplication];
    app.networkActivityIndicatorVisible = YES;
    dispatch_queue_t downloadQueue = dispatch_queue_create("data downloader", NULL);
    dispatch_async(downloadQueue, ^{
        (code here to download data and append it to the array....)
        dispatch_async(dispatch_get_main_queue(), ^{
            [self.gridView reloadData];
            app.networkActivityIndicatorVisible = NO;
        });
    });
    dispatch_release(downloadQueue);
}

**Comment by jonsterling** [comment]
Interesting; at first glance, that should work.

Can you provide a test project?

**Comment by jorfermo** [comment]
Is there any way I can send you the code privately? I tried your email jonsterling[at]me.com but it bounced

**Comment by jonsterling** [comment]
Sure. jonsterling[at]me.com is my email address, though; are you certain that's where it went?

Jon

**Comment by jonsterling** [comment]
That's fascinating. I'm getting these email notifications from GitHub in that very address… Don't quite know what to say…

**Comment by jonsterling** [comment]
"Message Size Violation" suggests that your my email provider doesn't want to accept so large an attachment. Can you upload it to a secret place and email me a link?
Jon

**Comment by jorfermo** [comment]
The zip is only 600KB....weird, I'm gonna hang it somewhere so that you can
download it

On Sun, Feb 5, 2012 at 9:08 PM, Jonathan Sterling <
reply@reply.github.com

**Comment by jorfermo** [comment]
I'm using gmail address.... Now I didn't attach anything but a link and this is the answer:

Delivery to the following recipient failed permanently:

```
jonsterling@me.com
```

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the recipient domain. We recommend contacting the other email provider for further information about the cause of this error. The error that the other server returned was: 554 554 5.7.0 Message Size Violation (state 18).

It seems there's some problem with your email server

**Comment by jonsterling** [comment]
I don't really understand how there could be a problem with my mail server, since I'm getting lots of email from various sources. I really have no idea what could be the problem.
