### ISSUE TITLE
Calling willSelectItemAtIndexPath with invalid index path

### ISSUE THREAD

**Issue by zoul** [kolinkrewinkel/KKGridView#107]
The `gridView:willSelectItemAtIndexPath:` delegate callback may be called with `NSNotFound` in `[indexPath index]` or `[indexPath section]`. (The stack trace is `_handleSelection` in `KKGridView` that calls `indexPathForItemAtPoint` where the index path with `NSNotFound` is created.) I don’t think it’s appropriate to call the delegate if we know the user is not selecting anything. Could we simply solve this by adding another condition on line 1406? Something like:

```
if (_delegateRespondsTo.willSelectItem && [indexPath index] != NSNotFound)
    indexPath = [_gridDelegate gridView:self willSelectItemAtIndexPath:indexPath];
```

Happy to send a pull request.

**Comment by jonsterling** [comment]
A very good point! I'm fixing this right now. Thanks!

**Comment by zoul** [comment]
This got broken by some of the recent commits, see my previous comment for a fix. Ah, and I don’t have the permissions to reopen the issue, so please somebody do that.

**Comment by zoul** [comment]
4cf370c7 might be also worth merging, as it restores the option for the delegate to cancel the selection and adds some comments that make the code a bit more clear.

**Comment by jonsterling** [comment]
Thanks for noticing the regression, @zoul... Can you open a pull request with the appropriate commits?

**Comment by zoul** [comment]
I’d love to, but I screwed up and landed the commits on a branch where they’re intermixed with other stuff. Can you cherry-pick dd12d4a (and possibly also 4cf370c)? Or if I open a pull request with more commits, will it make the cherry-picking easier for you?

**Comment by jonsterling** [comment]
Ah, I see, no worries :). I'll cherry-pick them, or if I don't get around to it, @kolinkrewinkel probably can.

**Comment by jonsterling** [comment]
Cherry picked.
