### ISSUE TITLE
-[KKGridView _layoutGridView] is huge / extremely deep

### ISSUE THREAD

**Issue by jonsterling** [kolinkrewinkel/KKGridView#11]
I'm wondering what people think about breaking `-_layoutGridView` into a few smaller methods. The reason I suggest this is that I think it's rapidly becoming “write-once, read-never” code. If the consensus is that this would be a good idea, I'm happy to tackle it.

**Comment by myell0w** [comment]
totally, wanted to open the same issue because this method is insane.

sent from phone

Am 31.07.2011 um 18:39 schrieb jonsterlingreply@reply.github.com:

**Comment by kolinkrewinkel** [comment]
as long as there are no issues with objc_messagesend speed.  including the arc 33% speed improvement ;)

**Comment by kolinkrewinkel** [comment]
were you going to do this now or later?

**Comment by kolinkrewinkel** [comment]
if you don't want to, i can do it.

**Comment by jonsterling** [comment]
I was planning on it, but if you wanted to do it, that's fine with me too. As for `objc_messageSend`, if we have a problem with that, we can always use plain C functions. But let's not worry about that just yet.

Also, omg, did we really get a 33% improvement from ARC?

**Comment by kolinkrewinkel** [comment]
Ok, I'll do it.  Watch the Getting Started with ARC & Objective-C Advancements in depth (I know one session is 322) for more details.

**Comment by jonsterling** [comment]
Cool.
