### ISSUE TITLE
Badges do not appear

### ISSUE THREAD

**Issue by ghost** [kolinkrewinkel/KKGridView#112]
In cellForItemAtIndexPath I put the following code:

cell.accessoryPosition = KKGridViewCellAccessoryPositionTopLeft;
cell.contentView.backgroundColor = [UIColor lightGrayColor];
cell.accessoryType = KKGridViewCellAccessoryTypeCheckmark;

No badge appears.  Am I missing something?

**Comment by kolinkrewinkel** [comment]
If you enable blended layers, do you see the outline of where the accessory should appear?

**Comment by ghost** [comment]
I found out two problems. The first problem I found is that failure-btn-pressed.png was misspelled as failure-btn-press.png in the bundle so that code could not load it up.

The other problem is that this file is missing so I can't put white checks on cells:
UIPreferencesWhiteCheck.png

**Comment by ghost** [comment]
I'll close it out because we have a checkmark bug now.
