### ISSUE TITLE
Footer views do not behave as expected

### ISSUE THREAD

**Issue by kolinkrewinkel** [kolinkrewinkel/KKGridView#13]
See UITableView for guidance.

**Comment by myell0w** [comment]
Well I don't know who fu***\* it up and am too lazy to search atm, but if you go back to my last commit 2ba72cacf9c155b7b378228a9e42f9109362f361 you can see that they are working as expected (at least for the test I used there) :)

**Comment by myell0w** [comment]
… but they are _very_ slow, so one might want to improve that
