### ISSUE TITLE
Always Call -gridView:cellForRowAtIndexPath:

### ISSUE THREAD

**Issue by kolinkrewinkel** [kolinkrewinkel/KKGridView#14]
I think we could do this with an `@synchronized` getter active-indexpath ivar that returns the appropriate `_visibleCell` in `-dequeueReusableCellWithIdentifier:`.
- Main reason: match `UITableView` behavior

**Comment by jonsterling** [comment]
Could you elaborate a little bit on what this issue means? I'd be happy to jump onto chat if you'd rather discuss it there also.
