### ISSUE TITLE
How to add UITextField above KKGridView? is it possible?

### ISSUE THREAD

**Issue by steve21124** [kolinkrewinkel/KKGridView#140]
I want to add UITextField above KKGridView. But KKGridView always stay below NavigationController bar and not stay below UITextField. 

from below screenshot UITextField overlay on top of KKGridView. The right behaviour is KKGridView below UITextField
http://i.imgur.com/9fd1x.png

**Comment by kolinkrewinkel** [comment]
Add the textfield to your grid view controller view, then call -bringSubviewToFront

**Comment by steve21124** [comment]
thanks. however, it still not pushing down KKGridView. May be because of the CGRectMake(10, 100, 120, 40). 
- (void)viewDidLoad
  {  
  UITextField\* textField = [[UITextField alloc] initWithFrame:CGRectMake(10, 100, 120, 40)];
  textField.borderStyle = UITextBorderStyleRoundedRect;
  [self.gridView addSubview:textField];
  [self.gridView bringSubviewToFront:textField];
  [super viewDidLoad];

**Comment by kolinkrewinkel** [comment]
Ah I see: don't add it to the grid view, add it to the grid's superview.

**Comment by steve21124** [comment]
thanks, it works!

**Comment by kolinkrewinkel** [comment]
No problem!
