### ISSUE TITLE
Scrolling png-backgroundview stutters

### ISSUE THREAD

**Issue by chrhansen** [kolinkrewinkel/KKGridView#149]
In my KKGridViewController sub-class I'm writing:
- (void)loadView
  {
  [super loadView];
  self.gridView.backgroundColor = [UIColor colorWithPatternImage:[UIImage imageNamed:@"myBackgrundImage"]];
  ...
  }

Because I want the background to scroll with the cells. "myBackgroundImage" is a png of a shelf so that each cell will seem like standing on the shelf as in th iBooks app. The png is only the height of on shelf, and there is room for 4-5 shelfs in iPad portrait.

The scrolling however is very bad and stutters a lot (the png is only abou 50-60 kB). If I change the background color to, say, scrollviewtexturedbackgroundcolor scrolling is perfect and smooth.

Am I doing something wrong? 

BR Christian

**Comment by zadr** [comment]
Try using -gridView:viewForRow:inSection: to provide a background view of an image shelf for each row, instead of a moving background view?

**Comment by chrhansen** [comment]
Thanks, will try first thing tomorrow.

**Comment by chrhansen** [comment]
Great! It works. Smooth scrolling with moving background. 

Any ideas to add views for rows that does not have cells? I have 4-5 rows and if only 2 contains cells -gridView:viewForRow:inSection: will only be called for those rows. I would like to have the shelfs populated where ever the user can see.
