### ISSUE TITLE
Scroll to Item at IndexPath

### ISSUE THREAD

**Issue by kolinkrewinkel** [kolinkrewinkel/KKGridView#15]
• See UITableView for guidance

**Comment by jonsterling** [comment]
For some reason, setting the content-offset to be the `y` of `-rectForCellAtIndexPath:` or whatever puts the cell somewhere in the middle of the screen. I'm not really sure what's going on here. Thoughts?

**Comment by kolinkrewinkel** [comment]
maybe the header view?

**Comment by jonsterling** [comment]
That's what I thought too, but assuming that the cells are being drawn in the rect returned by that method, you'd think that scrolling to it would bring you there as well. I'll have another look at it tomorrow night if nobody has gotten to it by then. Gotta go to bed now.

**Comment by kolinkrewinkel** [comment]
ok night  

–––––––––––––––––––––––
Kolin Krewinkel
kolin@kolinkrewinkel.com
(925) - 413 - 6180

**Comment by jonsterling** [comment]
Let's make this the next priority. Seems like it can start being used after this works.
