### ISSUE TITLE
App store reject

### ISSUE THREAD

**Issue by ghost** [kolinkrewinkel/KKGridView#150]
I have used KKGridView in my project (iOS 4 +) and my app got rejected.
Here is the response from apple :'

---

We found that your app uses one or more non-public APIs, which is not in compliance with the App Store Review Guidelines. The use of non-public APIs is not permissible because it can lead to a poor user experience should these APIs change. 

We found the following non-public API/s in your app:

gridView:viewForHeaderInSection:X

If you have defined methods in your source code with the same names as the above-mentioned APIs, we suggest altering your method names so that they no longer collide with Apple's private APIs to avoid your application being flagged in future submissions.

Additionally, one or more of the above-mentioned APIs may reside in a static library included with your application. If you do not have access to the library's source, you may be able to search the compiled binary using "strings" or "otool" command line tools. The "strings" tool can output a list of the methods that the library calls and "otool -ov" will output the Objective-C class structures and their defined methods. These techniques can help you narrow down where the problematic code resides.

**Comment by kolinkrewinkel** [comment]
Yeah, this is the second occurrence of this.  As a temporary fix, try changing the method name and orders; I'm going to open a DTS for this though..  Apple sitting on their piece of shit implementation and preventing us from doing any work on our own is annoying.

**Comment by ghost** [comment]
Yea, I did that. I refactored the code and renamed all methods to meshView:X
On an unrelated note, someone blogged about it on http://www.dimzzy.com/blog/2012/03/apple-is-working-on-grid-view/

**Comment by kolinkrewinkel** [comment]
Apple's had that grid view in iOS since Photos.app existed.

**Comment by ghost** [comment]
Interesting to see that only recently they have started rejecting apps which use gridView.

**Comment by kolinkrewinkel** [comment]
I'm pretty sure it corresponds with the implementation of a code decompile ad analyzer - they started consistently catching uses of private APIs back in 4.0 IIRC.  I'd love it if they released their own in iOS6, however.  They're much more capable than me, and it'd give us some competition if it lacked something I really wanted. :)

**Comment by mariosangiorgio** [comment]
I just got a rejection, with other methods than the one reported in this issue:

> We found the following non-public API/s in your app:
> 
> gridView:heightForHeaderInSection:
> gridView:titleForHeaderInSection:
> gridView:viewForHeaderInSection:
> 
> If you have defined methods in your source code with the same names as the above-mentioned APIs, we suggest > altering your method names so that they no longer collide with Apple's private APIs to avoid your application being > flagged in future submissions.

**Comment by kolinkrewinkel** [comment]
You'll have to change the method names. Add KK in front of those methods in the data source protocols, then adjust where the errors are.

**Comment by mariosangiorgio** [comment]
Do you want me to fork the project and create a pull request?

**Comment by amarchen** [comment]
I am confused. This issue is closed, but the proposed pull request was never merged.
@mariosangiorgio , did you get your app approved? After the modifications proposed?

And also do you remember if XCode validation was warning about these methods as well or if it looked fine until the rejection?

I am asking, because our app passes XCode validation just fine and sure I wouldn't like to create own patches to KKGrid if it's possible to use the master version.

**Comment by mariosangiorgio** [comment]
After I applied my patch the application got approved.
XCode is not complaining about that methods. Probably Apple has runs some stricter rules than the ones of the XCode validator.

**Comment by amarchen** [comment]
Thanks, @mariosangiorgio
