### ISSUE TITLE
reloadData issue

### ISSUE THREAD

**Issue by ShadyGhalab** [kolinkrewinkel/KKGridView#166]
i can't imagine how this method is too slow like this it's takes seconds when reload

**Comment by kolinkrewinkel** [comment]
Have you time profiled to find what the underlying issue was?

**Comment by ShadyGhalab** [comment]
it takes from 2 seconds to 3 when i search using UISearchBar - (void)searchBar:(UISearchBar *)searchBar textDidChange:(NSString *)searchText; from core data then reload the grid
- (void)searchBar:(UISearchBar *)searchBar textDidChange:(NSString *)searchText{
  
  if([searchText length] == 0) {
      [searchBar performSelector: @selector(resignFirstResponder)
                      withObject: nil
                      afterDelay: 0];
  
     // return;
  }
  
  if ([searchText isEqualToString:@""]){
      _fetchedResultsController = nil;
      [self fetchedResultsController];
  }
  else{
      //_fetchedResultsController = nil;
  
  ```
  [self fetchedResultsControllerWithSearchName:searchText];
  ```
  
  }
  
  [_gridView reloadData];

}

**Comment by kolinkrewinkel** [comment]
Your deadlock is probably the fetched results controller - it's doing that on the main thread.

**Comment by ShadyGhalab** [comment]
no i used static data in array and i have same problem

**Comment by kolinkrewinkel** [comment]
Try using the Time Profiler (http://developer.apple.com/library/mac/documentation/AnalysisTools/Reference/Instruments_User_Reference/TimeProfilerInstrument/TimeProfilerInstrument.html) by building and then profiling in Xcode. Let me know what the highest/slowest methods are once you run the slow block of code.

**Comment by ShadyGhalab** [comment]
after reload data -  gridView: cellForItemAtIndexPath: took about 0.8 for every cell to show it

**Comment by ShadyGhalab** [comment]
oooh i found the problem thnx , it's my fault . thank you very much

**Comment by kolinkrewinkel** [comment]
No problem.
