### ISSUE TITLE
Item Insertion

### ISSUE THREAD

**Issue by kolinkrewinkel** [kolinkrewinkel/KKGridView#17]
via -insertItemsAtIndexPaths:

**Comment by jonsterling** [comment]
Just wanted to note some bugs when inserting items:
1. http://cl.ly/0e2S3H0z2c3O2A35081y
2. http://cl.ly/2n1I1x3Z0h0q301b2M1B

**Comment by kolinkrewinkel** [comment]
Could you take a look into these?  I fixed the size issue after inserting but couldn't get that worked out.  I think the cells indexpath or calculated frame is incorrect.

**Comment by jonsterling** [comment]
Muchas gracias esse

**Comment by kolinkrewinkel** [comment]
No problem.
