### ISSUE TITLE
Non-sticky footer views?

### ISSUE THREAD

**Issue by jonsterling** [kolinkrewinkel/KKGridView#22]
I'm noticing that footer views stick to the bottom of the screen (analogous to header view behavior), whereas in UITableView, footer views are not sticky. I wonder whether it might not be better to allow this as an option, but have the default behavior be non-sticky. Thoughts?

This goes along with #16, since a default-ish looking section footer label would look rather silly if it were stuck to the bottom.

**Comment by kolinkrewinkel** [comment]
Footer views are sticky Jon.

**Comment by jonsterling** [comment]
My point is that section footer views are not supposed to be sticky, unless we are diverging significantly from the idiom established by `UITableView`.

**Comment by kolinkrewinkel** [comment]
LOL they stick.  Create a new project and use viewForFooterInSection

**Comment by myell0w** [comment]
afaik footer views stick with UITableViewStylePlain, which is related to our gridview-style.

I would still second an option (Delegate?) for making header and footer views non-sticky.

sent from phone

Am 03.08.2011 um 19:26 schrieb jonsterlingreply@reply.github.com:

**Comment by jonsterling** [comment]
Goodness gracious, I feel so silly. Please ignore this issue.

**Comment by myell0w** [comment]
nevermind, I had the same 'problem'. wasn't aware that they stick because I never used footerViews.

sent from phone

Am 03.08.2011 um 19:42 schrieb jonsterlingreply@reply.github.com:
