### ISSUE TITLE
sendSubviewToBack

### ISSUE THREAD

**Issue by myell0w** [kolinkrewinkel/KKGridView#24]
I know I'm to blame for this but I wanted to implement a correct behaviour first before I start to optimize. I'm not sure how this method is implemented internally but I expect the high amount of calls to sendToBack to be rather slow. 

Goal is to get currently sticking header/footer to be on top of other views. A simple bringSubviewToFront isn't working, since it then is on top of the UIScrollView - scrollIndicator (should we open a rdar/bug for this?).

Maybe bringToFront + exchange with second-frontmost subview (which should be the scrollIndicator then) works.

Thoughts?

**Comment by kolinkrewinkel** [comment]
It's only called when it's added, I don't think it's too bad.

**Comment by jonsterling** [comment]
Is this still a relevant issue? If not, let's close it…
