### ISSUE TITLE
renderQueue?

### ISSUE THREAD

**Issue by steipete** [kolinkrewinkel/KKGridView#27]
Hi guys,

i finally have time to look into KKGridView, and already found/working on some issues.

I'm curious, what's the reasoning behind renderQueue and the dispatch_sync? (_layoutGridView, KKGridView.mm)
I've never seen such a pattern - AFAIK you're not allowed to make UIKit-changes except in the main thread, so we're already guaranteed that no two render operations run at the same time. Am I overlooking sth?

**Comment by kolinkrewinkel** [comment]
The render queue assures that the cells are rendered synchronously, in order, and with the highest priority.  The threading assures the app is free to do whatever it needs with as little possible interruption from the grid.  We noticed a moderate performance increase with this.

**Comment by jonsterling** [comment]
I'd like more discussion on this. At first glance, Peter appears to be right, since sending UIKit messages on a thread other than the main thread is documented as a no-no.

**Comment by kolinkrewinkel** [comment]
This queue is on the main thread AFAIK otherwise the UI wouldn't update at all.

**Comment by jonsterling** [comment]
Sounds reasonable. Can you find it documented that serial queues execute on the main thread?

**Edit:** Unless you find something to the contrary, I don't think it's actually guaranteed that serial queues will execute on the main thread. Hence, to be safe, we probably ought to wrap all UIKit updates in `dispatch_async(dispatch_get_main_queue(), ^{});` blocks.

**Comment by kolinkrewinkel** [comment]
I'll ask Indragie.  I got the idea from him.

**Comment by steipete** [comment]
Still, i'm not convinced that there's any advantage in using such a queue. Performance-wise, all it should bring is a slightly speed loss, GCD is fast, but there's still some overhead.

**Comment by jonsterling** [comment]
Only way to find out is to test. The reason we're using a queue in the first place is that @kolinkrewinkel believed that it resulted in a net speed increase when he tried it. If that's no longer the case, it should be excised.

**Comment by Gi-lo** [comment]
I think what the queue does is bundling all the update actions and put it at the end of the main runloop. I may be wrong though...

**Comment by steipete** [comment]
No, it doesn't. If you use dispatch_sync, it's executed right within the code flow.
