### ISSUE TITLE
Ditching KKGridView header

### ISSUE THREAD

**Issue by kolinkrewinkel** [kolinkrewinkel/KKGridView#3]
i think we can hold a vector of the stickpoints and stuff - we should get rid of the requirement to have a KKGridViewHeader returned.

**Comment by jonsterling** [comment]
Did you see my modifications? Consumer supplies their own `UIView`. `KKGridViewHeader` is an `NSObject` class which wraps a `UIView` with some other data; it's used internally and never seen by consumers.

I'm really OK with either approach, though.

**Comment by kolinkrewinkel** [comment]
No I didn't really look _guilty face_.  That works perfectly for me, though.  We just need to make sure, if we do provide it, that a function that returns all headers returns the internal UIView and not our wrappery thing.
