### ISSUE TITLE
Adding new items *fast* results in holes

### ISSUE THREAD

**Issue by steipete** [kolinkrewinkel/KKGridView#30]
We need to rework some code in - (void)_performUpdate:(KKGridViewUpdate *)update withVisiblePaths:(NSArray *)visiblePaths

See screenshot, if I press + rapidly in the example project:

https://skitch.com/steipetee/fuwcc/ios-simulator

**Comment by kolinkrewinkel** [comment]
I think the updates are not being handled in the order received - in fact I'm certain of this.  I believe this is why.  We need to order them by date added or something..

**Comment by zwaldowski** [comment]
Well it's good to know that I haven't completely lost my mind...

**Comment by kolinkrewinkel** [comment]
LOL

**Comment by steipete** [comment]
No, the update order isn't the problem. Compile in Xcode 4.2 and enable slow animations in the Simulator. You see that on rapid inserts, the animation performs, then the cells move to a different position on animation end - as if they're not correctly saved before starting the animation.

Also, you may wanna honor the "finish" flag in the animation blocks...

**Comment by kolinkrewinkel** [comment]
You're sure the updates aren't incorrectly sorted?  The only ordering they have is a compare: based on index path.

**Comment by kolinkrewinkel** [comment]
Also: is that because animations occur once the cells come in to view?

**Comment by jonsterling** [comment]
Yeah, this isn't even close. Even on non-fast updates, it looks hilarious…

**Comment by kolinkrewinkel** [comment]
I agree, it doesn't slide over anymore at all or even look how it needs to.

**Comment by kolinkrewinkel** [comment]
Here's the issue in logging (testable on your machine by using Console/NSLog) http://krwnk.me/1W372q2A19301G352F3M

**Comment by kolinkrewinkel** [comment]
Ordering is also wrong.  http://krwnk.me/3a0g1L3H3r3g05183n2L
