### ISSUE TITLE
How to? overflow items in sections goes to next page?

### ISSUE THREAD

**Issue by steve21124** [kolinkrewinkel/KKGridView#32]
How to? overflow items in sections goes to next page instead of have the grid box list below to next row?
This will be similar to Pulse app where the overflow grid items in section on the page column inside the section instead of fall below the current row.
Is this feature supported?

**Comment by jonsterling** [comment]
I'm afraid I don't quite follow, old scout. What exactly do you mean by next page?

**Comment by jonsterling** [comment]
I'm going to close this issue, since I don't fully understand what the question is. If this is still a problem, and you would like to elaborate, let me know and I'll reopen it!
