### ISSUE TITLE
Is there quick document/code to use demo example in xcode 4.0?

### ISSUE THREAD

**Issue by steve21124** [kolinkrewinkel/KKGridView#34]
I have compiled libKKGridView.a, I want to use in Xcode 4.0 (ios SDK 4.x), I think the demo code using ios 5.0. Is there example that use ios 4.x?

**Comment by myell0w** [comment]
KKGridView can be used using iOS 4, but not using Xcode 4.0 since KKGridView uses ARC, which is only supported by the newest LLVM compiler. Therefore you have to use Xcode 4.2 Beta.

Am 30.08.2011 um 10:27 schrieb steve21124:
