### ISSUE TITLE
reloadData doesn't ... reload data

### ISSUE THREAD

**Issue by blackgold9** [kolinkrewinkel/KKGridView#35]
The reload data call should actually reload data (to match UITableView conventions).
What it is currently appears to be a reset data call.
I added a _layoutVisibleCells call at the end of the reload data method to accomplish this. 

Would that break other areas of the grid? I see reloadData called when cell sizes/spacing is set. Should there be an internal "Reset" method that can be used in those other methods, and also in the reloadData call?

Not sure i fully understand the implications.

**Comment by kolinkrewinkel** [comment]
You have it right.  The difficult bit is reloading 'data' though, for we're not passed data values like NSTableView.  We leave it up to the data source to customize.
