### ISSUE TITLE
Dispatch Queue Leak

### ISSUE THREAD

**Issue by kolinkrewinkel** [kolinkrewinkel/KKGridView#36]
I can't add a dealloc method because of ARC, and thus can't call dispatch_release().  Help?

**Comment by jonsterling** [comment]
Not true! You can actually implement `-dealloc`. You just can't send `-dealloc`.

To be clear, your implementation can look like:

``` objc
- (void)dealloc {
  dispatch_release(_queue);
}
```

The `super` call will be added by the compiler.

**Comment by kolinkrewinkel** [comment]
Weird, the compiler yelled at me last time I tried — I must've included the super call.  Thanks!

**Comment by myell0w** [comment]
you can add dealloc

sent from phone

Am 04.09.2011 um 01:33 schrieb kolinkrewinkelreply@reply.github.com:
