### ISSUE TITLE
How to subclass the cells?

### ISSUE THREAD

**Issue by mamcx** [kolinkrewinkel/KKGridView#37]
In the wiki say that this could work as the springboard.

I can draw the cells, but adding new subviews on the cells block the selection code, and the delegates are not fired for selection.

Also, I try loading from a nib with the same results (the cells are show, but not selection work).

**Comment by kolinkrewinkel** [comment]
Try using userInteractionEnabled: NO on subviews.  Also: I'm not planning to add XIB support cause it's slow, if it requires work.

**Comment by mamcx** [comment]
I try that a not work...

## 

Mario A.Montoya
Gerente
http://www.elmalabarista.com

Haz pedidos & facturas con tu iPhone: http://www.bestsellerapp.com

**Comment by mamcx** [comment]
Also, I add the views purely by code:
- (KKGridViewCell *)gridView:(KKGridView *)_gridView
  cellForItemAtIndexPath:(KKIndexPath *)indexPath

{

```
NSString *cellID = [HomeCellView cellIdentifier];

HomeCellView *cell = (HomeCellView *)[gridView
```

dequeueReusableCellWithIdentifier:cellID];

```
if (cell == nil) {

    /*[[NSBundle mainBundle] loadNibNamed:@"HomeCell" owner:self
```

options:nil];

```
    cell = self.homeCell;

    self.homeCell = nil;*/

    cell = [[HomeCellView alloc] initWithFrame:CGRectMake(0,0,
```

HOME_WIDTH, HOME_HEIGTH)];

```
    cell.title = [[UILabel alloc] initWithFrame:CGRectMake(0,0,
```

HOME_WIDTH, 36)];

```
    cell.backgroundColor = [UIColor grayColor];

    cell.title.backgroundColor = [UIColor blackColor];

    cell.title.opaque = YES;

    [cell addSubview:cell.title];

}



return cell;
```

}

And don't work neither...

**Comment by kolinkrewinkel** [comment]
Did you ever figure this out?
