### ISSUE TITLE
Can't use in project without ARC support

### ISSUE THREAD

**Issue by xtazz** [kolinkrewinkel/KKGridView#41]
You write in README: "Remember that your project need not use ARC to include KKGridView"
But this is not excactly true - you can't use it (even using binary file built with LLVM 3.0) in projects which are building with LLVM 2.x, since you have to include headers which contain new ARC keywords like 'strong', 'unsafe_unretained' etc. If I comment property definitions with new keywords in KKGridView headers my project builds successfully and grid is working. So it would be nice if some condition vars will be present to allow users with legacy compilers use this library.

Thanks!

**Comment by myell0w** [comment]
You don't have to use ARC, you just have to use an ARC-compliant compiler (which is LLVM 3.0 which means you have to use Xcode 4.2 Beta). We don't plan on adding conditionals and cluttering the code-base for older compilers.

Am 21.09.2011 um 14:11 schrieb Peter:

**Comment by steipete** [comment]
Single only problem is that you can't use it _right now_, as 4.2 builds can't be submitted. But this problem will fix itself in a few days...

**Comment by jonsterling** [comment]
Exactly! Since KKGridView isn't yet stable enough to be used in an app shipping today, it doesn't even matter that you can't submit 4.2 builds, as far as I'm concerned.

**Comment by kolinkrewinkel** [comment]
@jonsterling This is exactly the intent!
