### ISSUE TITLE
Is there an option not to select a cell when a scroll starts?

### ISSUE THREAD

**Issue by horaceho** [kolinkrewinkel/KKGridView#42]
When a scroll start on top of a cell, the cell is selected. 

Is there a way to change this default behavior? Such that the cell is only selected when the grid is not scrolled (touch-moved), which works like the UITableView.

**Comment by kolinkrewinkel** [comment]
Yes, we're working on fixing the cell selection so it's more solid.  Thanks.

**Comment by jonsterling** [comment]
This seems no longer to be an issue; I'm going to close this now. If you're still having problems with this, feel free to let us know here.
