### ISSUE TITLE
Deselection of grid items

### ISSUE THREAD

**Issue by cmeranda** [kolinkrewinkel/KKGridView#46]
Is there a way to deselect grid cells once tapped, as in a table view?

**Comment by kolinkrewinkel** [comment]
Programmatically or through the UI?

**Comment by jonsterling** [comment]
Unless I'm much mistaken, there doesn't seem to be exposed an API to select or deselect cells. I'd mentioned to Kolin that I'd work on that a while back, and I still might if I get a chance. If anyone wants to do it, though, that's fine with me! I would mirror the `UITableView` interface as closely as possible.

**Comment by kolinkrewinkel** [comment]
yea, i'll do this later.

**Comment by jonsterling** [comment]
I do like you use the word “yea”; perhaps you should append “verily”? And maybe prepend “Lo”.

**Comment by kolinkrewinkel** [comment]
meh, i'm not that old english to use those.  i'm only 1/2 as bad as you :p

**Comment by cmeranda** [comment]
Through the API was the intention. Cheerio.

**Comment by cmeranda** [comment]
Whoops, apparently my literacy is limited, didn't mean to close that, just comment.

**Comment by kolinkrewinkel** [comment]
Ok, I'll add this in later today.

**Comment by cmeranda** [comment]
Awesome!

**Comment by kolinkrewinkel** [comment]
No problem! :)
