### ISSUE TITLE
scrollview position not what is expected on rotation

### ISSUE THREAD

**Issue by jjfster** [kolinkrewinkel/KKGridView#48]
When rotating, I would expect the same cells to be shown when rotating from portrait to landscape and vice versa (or at least something close to that).

Seems the scrollview position gets way off.  Tested by adding numbered labels to demo and adding 100 or so cells to first section.

I added some code to "fix" to the rotation delegates, but it's a hack at best.

Am I missing something here?  For the end-user, if they see images in the visible cells in portrait, they should see those same images when rotating to landscape (within a certain bounds of course), right?

**Comment by kolinkrewinkel** [comment]
Yes, this makes sense.  I'll take a look and see what UITableView's behavior is..

**Comment by kolinkrewinkel** [comment]
Lo, it appears that UITableView has the same issue.  This one may not be fixable without hacks and may be best left alone.  Thoughts, @jonsterling?

**Comment by jonsterling** [comment]
Hmm. I've been playing around, and it seems all right to me. It's not perfect, but it seems at least as good as `UITableView`. As such, I'mma close this issue.

If anyone has ideas for improving this (in a non-hacky way), feel free to discuss it here or (better) submit a pull request! :)
