### ISSUE TITLE
Help newcomer to build demo please!

### ISSUE THREAD

**Issue by peterlondon1** [kolinkrewinkel/KKGridView#53]

**Comment by peterlondon1** [comment]
worked it out, sorry to have posted this.

**Comment by SpacyRicochet** [comment]
@peterlondon1 I'm having issues as well. Could you post whatever you're problem was and what your solution was?

**Comment by blommegard** [comment]
Open up the workspace and run it within that.

**Comment by SpacyRicochet** [comment]
Guess I need to read up on workspaces. Thanks :)
