### ISSUE TITLE
block-per-method is poor substitute for protocols

### ISSUE THREAD

**Issue by dhennessy** [kolinkrewinkel/KKGridView#54]
I don't understand why you replaced the standard cocoa convention of dataSource and delegate protocols with a block per method.  This makes the calling code much uglier to write. Please consider reinstating the original protocol methods.

ps If you really want to use blocks for every method, then a better approach would be to create a proxy object that implements KKGridViewDataSource and has a property for each method block.

**Comment by jonsterling** [comment]
Completely agreed. In fact, I did initially suggest such a proxy object. After having used the current way a few times, the novelty of blocks has certainly worn off to some degree.

Blocks are supposed to save code, but I ended up writing more code when I had them. And Xcode's completion was really bad.

**Comment by jonsterling** [comment]
I'd love to get some conversation on this… I'm definitely of the opinion that the formal protocols should be reinstated, and that we provide another class (perhaps `KKGridViewBlocksDelegate`) with the various block properties. It's a proxy which redirects messages to the appropriate block.

I think that we should maintain the canonical way to handle custom behavior (delegation with formal protocols), and provide the option to use blocks for those for whom it would be more concise.

**Comment by jonsterling** [comment]
Maybe when I have time next week, I'll mess with this and see if I can put together a better solution.

**Comment by dhennessy** [comment]
It's a shame there aren't any comments from the original project authors on this topic. I'd be interested in seeing your work.

**Comment by myell0w** [comment]
@jonsterling is one of the original project authors ;)

**Comment by steipete** [comment]
+1, plus you have to worry breaking retain cycles/dangling pointer issues when using blocks here.

**Comment by dhennessy** [comment]
> @jonsterling is one of the original project authors ;)

LOL. I guess that increases the chances of the protocol support returning. :)

**Comment by zwaldowski** [comment]
+1.  Block properties and protocol implementations have a lot of conceptual overlap, but table/grid view methods are simply much too long. Block properties are helpful for keeping your code linear (both visually and in terms of scope). Table/grid view callbacks are nonlinear and should be as such in the implementation.

**Comment by kolinkrewinkel** [comment]
Both methods are now available.

**Comment by jonsterling** [comment]
Huzzah! Closing issues like a boss.

**Comment by dhennessy** [comment]
Thanks!  Looking forward to trying it out.
