### ISSUE TITLE
backgroundView -setHidden: doesnt seem to work

### ISSUE THREAD

**Issue by jamesmcc** [kolinkrewinkel/KKGridView#55]
I am trying to have an image in the background of the gridview, so I thought the following code would hide the control background and allow the image to show through similar to a tableview but seems to have no affect

``` objc
[self.gridView.backgroundView setHidden: YES];
```

My iOS coding skills are basic so I might be completely wrong, if there is a better a way then I am happy to learn.

**Comment by kolinkrewinkel** [comment]
I'm pretty sure backgroundView is unimplemented, so that's probably why. I'll take a look in a bit. :)

**Comment by zadr** [comment]
FWIW, I implemented backgroundView in https://github.com/zadr/KKGridView/commit/d9d683bb4516e2ca34faedeb8433d044dc6bb231 and https://github.com/zadr/KKGridView/commit/a69158a0dcb76dd0d3362798acf48530d01dbad9. They should cherry-pick over cleanly.

(I'd add a pull request, but, there are other commits that would get pulled over that you might not want — linker changes, primarily.)

// day-later-edit: https://github.com/zadr/KKGridView/commit/25c8455c12a94d4e4299e62e585d0b866d0753da should also be cherry-picked over; it has some better logic to ensure that the view hierarchy is always ordered properly, and the background view frame is always equal to the visible bounds.
