### ISSUE TITLE
Still can't archive

### ISSUE THREAD

**Issue by dj-jqpub** [kolinkrewinkel/KKGridView#62]
Hi! I see that you included some integration info in the readme. I followed it to the T and it works...until you try archiving it, still doesn't work, it just can't find KKGridView header. I hate to be a pain in the ass but I would really hate to abandon this component for another one because as I said once before, it is the best I've come across so far, but I'm sure you understand that if I can't build an ipa (and of course, if I can't build an ipa, I can't submit to app store) then I can't use this component and that would really be a shame. :)

**Comment by kolinkrewinkel** [comment]
I'm not really sure.. @alloy and @jonsterling may know as they know the Pods/static library stuff better than I do, respectively.

**Comment by alloy** [comment]
This is a known bug with Xcode 4… :(

What we did in CocoaPods was to replace the use of a ‘header build phase’, for the library target, by a normal ‘copy files phase’. This fixes the issue with archiving, however, we ran into issues with Xcode importing headers twice after, even after cleaning. What we do now, which fixes all issues, is to not let Xcode copy any headers at all, but instead set the `HEADER_SEARCH_PATH` of the user’s app target to where the headers of the library are.

HTH

**Comment by dj-jqpub** [comment]
It seems to be working with the mod you suggested. Thanks a million! I would suggest putting this in the readme so that others don't get bitten by this issue (I can do it when I get some time, not like you guys have a bunch of time either :)). Damn buggy Xcode! :)

**Comment by kolinkrewinkel** [comment]
I'll be sure to add this to the readme. Thanks Eloy. :)
