### ISSUE TITLE
Any other way to include the library?

### ISSUE THREAD

**Issue by seivan** [kolinkrewinkel/KKGridView#64]
Is there any other way to include the library without going through the workspace hassle on existing projects?

**Comment by jonsterling** [comment]
No that I know of. You could just include the code in your project, but you'd have to mess with internal imports to get them to work.

We're doing our best to enforce the best practice, which is to use workspaces with static libraries. However, I think some work has been done to integrate KKGridView with CocoaPods (which is supposed to handle the workspace wrangling for you). I have no experience with CocoaPods, though, so I don't know the specifics of how it works.

**Comment by jonsterling** [comment]
OK to close this?
