### ISSUE TITLE
Use AssetsLibrary for Demo

### ISSUE THREAD

**Issue by jonsterling** [kolinkrewinkel/KKGridView#75]
- each section is an album
- each item is a photo

As discussed in #74.

**Comment by kolinkrewinkel** [comment]
I've almost finished this in my local branch - the way I'm doing this now it's set up to retain the assets and lazy load the thumbnails.. Sound good?

**Comment by jonsterling** [comment]
Sounds good to me… When you've finished it, why don't you push it to a topic branch and we can merge it into master afterwards?
