### ISSUE TITLE
ARC

### ISSUE THREAD

**Issue by myell0w** [kolinkrewinkel/KKGridView#8]
Any reasons this is not in ARC?

**Comment by kolinkrewinkel** [comment]
Doesn't ARC require iOS5+?

**Comment by myell0w** [comment]
Not exactly, ARC also works with iOS 4, but zeroing weak references are missing in iOS 4, so no __weak.

Am 30.07.2011 um 15:23 schrieb kolinkrewinkel:

> Doesn't ARC require iOS5+?
> 
> Sent from my iPhone
>

**Comment by myell0w** [comment]
I'm not sure about ARC and Objective-C++ though, anyone got information on that?

Am 30.07.2011 um 15:23 schrieb kolinkrewinkel:

> Doesn't ARC require iOS5+?
> 
> Sent from my iPhone
>

**Comment by kolinkrewinkel** [comment]
That's why I want to stick with memory management - it's not bad anyway.

**Comment by myell0w** [comment]
Well it's not bad per se, but ARC is new and fancy ;) 

No to be more serious, ARC is definitely easier on the eyes and it is especially very "easy" to get a leak if you prefer to use ivars directly instead of properties.
Also ARC can do some pretty handy performance optimizations that turn out to be faster than manual management in a lot of cases, since the compiler can do optimizations we can't do (if we stick to the rules of memory management).

Am 30.07.2011 um 15:27 schrieb kolinkrewinkel:

> That's why I want to stick with memory management - it's not bad anyway.
> 
> Sent from my iPhone
>

**Comment by kolinkrewinkel** [comment]
If you want then, you can convert it to ARC.  Just make sure it works on ios4 cause it needs to work for stratus. :)

**Comment by jonsterling** [comment]
Yeah, ARC works great with Objective-C++. I foresee two issues:
1. It's going to be more painful to deal with toll-free bridging. I'd suggest just excising our calls to CF-functions if it gets too annoying.
2. Continuous testing: I have no iOS 4 devices. Can one of us commit to testing every major version against iOS4?

**Comment by myell0w** [comment]
Yeah you have to be be a bit more verbose and precise with toll-free bridging, but it works. I still haven an iOS 4 device but can't promise for how long. My company though will definitely have them for the next year or so :) In theory there shouldn't be any difference between ARC on iOS 5 and iOS 4 (except __weak of course), but yeah theory and real world can be two different things :)

@jonsterling: happy birthday btw!

Am 30.07.2011 um 19:35 schrieb jonsterling:

**Comment by kolinkrewinkel** [comment]
Oh yeah I forgot! Happy birthday Jon! 

I have multiple iOS 4 device to test on.

**Comment by kylehickinson** [comment]
I just committed some ARC support... it's only part though seeing as we still have to worry about "CFDictionarySetValue((CFMutableDictionaryRef)_reusableCells, identifier, [NSMutableSet set]);" this sort of thing... I don't really wanna get into using objc_unretainedPointer/objc_unretainedObject until it's final since I'm pretty sure they're going to be changing them in the near future

**Comment by kylehickinson** [comment]
Also didn't mean to close it there :P

**Comment by kolinkrewinkel** [comment]
I'm going to go ahead and remove all the ifdefs since ARC is apparently supported on iOS 4

**Comment by kylehickinson** [comment]
why don't you just rollback to the previous commit?

**Comment by kolinkrewinkel** [comment]
The previous commit didn't have ARC support?

**Comment by kylehickinson** [comment]
[eb30289](https://github.com/kolinkrewinkel/KKGridView/commit/eb3028970515a871c37af6efca71e130e543537c) the one right before my commit, I'm the only one who added anything to do with ARC

**Comment by kolinkrewinkel** [comment]
Yeah I want the ARC.  We just don't need the ifdefs.

**Comment by kylehickinson** [comment]
The ifdef's are there so that anyone can compile the code regardless of if they are using ARC or not.  If you want to have 2 different branches though thats cool

**Comment by kolinkrewinkel** [comment]
Since this is a subproject, we can have ARC on while the developer's main project has ARC off.

**Comment by kolinkrewinkel** [comment]
The app I'm going to use this for initially has ARC off, it still works with ARC on.

**Comment by kolinkrewinkel** [comment]
Ok setting up ARC through Xcode, hold off from committing everyone please. :)

**Comment by kolinkrewinkel** [comment]
I think this is pretty well done.. I'll close this issue but feel free to reopen.

**Comment by jonsterling** [comment]
Thanks for the birthday wishes, everyone!
