### ISSUE TITLE
-gridView:willDisplayCell:atIndexPath never gets called

### ISSUE THREAD

**Issue by hermanolsson** [kolinkrewinkel/KKGridView#80]
`-gridView:willDisplayCell:atIndexPath` on `gridDelegate` never gets called; it seems to be a spelling mistake in the `-respondsToSelector:` check. Want me to make a pull request, or can you just fix it? =)

**Comment by jonsterling** [comment]
Oops! Sorry about that. I can fix that tomorrow (or we're happy to accept pull requests). Sorry for the inconvenience!
