### ISSUE TITLE
Crashing on iOS 4.3

### ISSUE THREAD

**Issue by constantine-fry** [kolinkrewinkel/KKGridView#88]
When trying to run my app with KKGridView on iOS 4.3 the application crashes on runtime and stops inside the init of KKGridView (line:163@KKGridView.h):

dyld: lazy symbol binding failed: Symbol not found: _objc_storeStrong
  Referenced from: /Users/fry/Library/Application Support/iPhone Simulator/4.3.2/Applications/AE373D67-59F0-4356-B985-F8C8BCE0C2B9/MyApp.app/MyApp
  Expected in: /Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator4.3.sdk/System/Library/Frameworks/Foundation.framework/Foundation

dyld: Symbol not found: _objc_storeStrong
  Referenced from: /Users/fry/Library/Application Support/iPhone Simulator/4.3.2/Applications/AE373D67-59F0-4356-B985-F8C8BCE0C2B9/MyApp.app/MyApp
  Expected in: /Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator4.3.sdk/System/Library/Frameworks/Foundation.framework/Foundation

**Comment by steipete** [comment]
If you're compiling KKGridView as a subproject, make sure that you set the minimum deployment target to iOS4. You're missing libarclite here.

**Comment by constantine-fry** [comment]
how can i add libarclite to project?

**Comment by jonsterling** [comment]
See http://developer.apple.com/library/ios/#documentation/ToolsLanguages/Conceptual/Xcode4UserGuide/Building/Building.html to add libraries to your target.

**Comment by constantine-fry** [comment]
the problem was that I did not know where libarclite. i found it and resolved my problem. thanks a lot.
