### ISSUE TITLE
Detecting iOS 5 Deployment Target at compile time

### ISSUE THREAD

**Issue by myell0w** [kolinkrewinkel/KKGridView#9]
I wanted to add the following macro:

```
#if __IPHONE_OS_VERSION_MIN_REQUIRED >= 50000
   #define __kk_weak weak
#else 
  #define __kk_weak unsafe_unretained
#endif
```

to use zeroing weak references when deployment target is set >= iOS 5.0.
Apparently this doesn't work, __IPHONE_OS_VERSION_MIN_REQUIRED is always 40000 for me, even if I set deployment target to 5.0. Anyone has a better idea on how to solve this (or why this isn't working)?

**Comment by kolinkrewinkel** [comment]
Take a look at availability.h (shortcut in prefix.pch)
