### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by alleus** [kolinkrewinkel/KKGridView#92]
Is it just me, or is the scrolling performance for `KKGrdiView` really bad? I'm trying it out on a first generation iPad with about 30 cells, and I'm getting a very low FPS. I did some basic profiling with Instruments and among other things found three points that are taking up a lot of processing time:
1. In all but one of the custom setters in `KKGridViewCell` includes a `[self layoutSubviews]`, where they instead should just flag for relayout with `[self setNeedsLayout]`. This one is a biggie :)
2. There is caching of the number of items in all sections in `KKSectionMetrics.itemCount`, but `KKGridView` asks the delegate again and again anyway. Since the delegate method might include some time consuming logic, the cached number should be used instead.
3. `[KKGridView visibleIndexPaths]` is intensively called and seems to represent a big part of the running time of the calculations. Maybe this could also be cached?

I've made some adjustments regarding bullet 1 and 2 in [my fork](https://github.com/alleus/KKGridView/commits/master) of the repo. Let me know what you think about it :)

**Comment by jonsterling** [comment]
Thanks for looking into this. I'm definitely on your side with respect to #1, and I think you're most likely right about #2. I'd like to bring in @kolinkrewinkel on this to see what he thinks. I think my very act of mentioning him will have sent him a notification, in fact.

The visible index paths change so frequently (basically, whenever you scroll) that I don't know how much help it would be to cache them, but if you have any thoughts on this, we're definitely open to hearing them.

**Comment by alleus** [comment]
By the way, my fixes on my fork was very quickly put together and weren't very clean (nor functioning in all cases I realized...) But the core principles of my fixes is still valid ;)

**Comment by jonsterling** [comment]
Sure.

**Comment by jonsterling** [comment]
All right. I've incorporated your first and second changes (thanks!). I think that the third bears some discussion and further thought…

Thanks for taking the time to work on this stuff!

**Comment by alleus** [comment]
Looks great, although, I see that my second performance bullet is still not really fixed. There are 3 `[_dataSource gridView:self numberOfItemsInSection:section]` calls in `KKGridView` still.

I'm happy to help. This component is showing a lot of promise :)

**Comment by jonsterling** [comment]
I've removed the call in `-_heightForSection:`. The one in `-visibleIndexPaths`, however, is a bit more delicate; I'm working on fixing that now.
